# Generated by Django 4.1.7 on 2023-02-27 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='organizations',
        ),
        migrations.AddField(
            model_name='user',
            name='organizations',
            field=models.ManyToManyField(to='user.organization', verbose_name='Организация'),
        ),
    ]
